#!/bin/sh

USAGE="Usage: $0 data-name CSS-selector URI"
DATA_PATH="${DATA_PATH:-$HOME/.webupdates}"

set -e

name="$1"
css_selector="$2"

if test -z "$3"
then
  echo "$USAGE" 1>&2
  exit 1
fi
shift 2

mkdir -p "$DATA_PATH"
data_file="$DATA_PATH/$name"
test -e "$data_file" || touch "$data_file"

webg --squeezed-text --css-selector="$css_selector" "$@" > "$data_file.new"
trap "rm -f '$data_file.new' '$data_file.diff'" EXIT

if test -s "$data_file.new"
then
  exit
fi

if diff -u "$data_file" "$data_file.new" > "$data_file.diff"
then
  exit
fi

cat - "$data_file.diff" <<EOF
## ${name}

$@

EOF
mv "$data_file.new" "$data_file"
